export const Symbols = {
  ConfigInterface: Symbol.for('ConfigInterface'),
  LoggerInterface: Symbol.for('LoggerInterface'),
  DatabaseConnectionInterface: Symbol.for('DatabaseConnectionInterface'),
  DatabaseInterface: Symbol.for('DatabaseInterface'),
  DatabaseContextInterface: Symbol.for('DatabaseContextInterface'),
  TransactionalExecutorInterface: Symbol.for('TransactionalExecutorInterface'),
  CommandBusInterface: Symbol.for('CommandBusInterface'),
  CommandHandlerRegistryInterface: Symbol.for(
    'CommandHandlerRegistryInterface',
  ),
  MediaRepositoryInterface: Symbol.for('MediaRepositoryInterface'),
  RouterInterface: Symbol.for('RouterInterface'),
  ListenerProviderInterface: Symbol.for('ListenerProviderInterface'),
  EventDispatcherInterface: Symbol.for('EventDispatcherInterface'),
  FailedEventRepositoryInterface: Symbol.for('FailedEventRepositoryInterface'),
  ApplicationVersionRepositoryInterface: Symbol.for(
    'ApplicationVersionRepositoryInterface',
  ),
  UuidRepositoryInterface: Symbol.for('UuidRepositoryInterface'),
  NotificationServiceInterface: Symbol.for('NotificationServiceInterface'),
  WebSocketServerInterface: Symbol.for('WebSocketServerInterface'),
  WebSocketMessageParserInterface: Symbol.for(
    'WebSocketMessageParserInterface',
  ),
  ErrorHandlerMiddleware: Symbol.for('ErrorHandlerMiddleware'),
  CorsMiddleware: Symbol.for('CorsMiddleware'),
  TimeoutMiddleware: Symbol.for('TimeoutMiddleware'),
  NotFoundMiddleware: Symbol.for('NotFoundMiddleware'),
  ApplicationFactoryInterface: Symbol.for('ApplicationFactoryInterface'),
  FilesystemInterface: Symbol.for('FilesystemInterface'),
  ClockInterface: Symbol.for('ClockInterface'),
  ControllerResolverInterface: Symbol.for('ControllerResolverInterface'),
  RouteProviderInterface: Symbol.for('RouteProviderInterface'),
}
