export const Symbols = {
  ConfigInterface: Symbol.for('ConfigInterface'),
  LoggerInterface: Symbol.for('LoggerInterface'),
  DatabaseConnectionInterface: Symbol.for('DatabaseConnectionInterface'),
  DatabaseInterface: Symbol.for('DatabaseInterface'),
  MediaRepositoryInterface: Symbol.for('MediaRepositoryInterface'),
  RouterInterface: Symbol.for('RouterInterface'),
  Container: Symbol.for('Container'),
  ListenerProviderInterface: Symbol.for('ListenerProviderInterface'),
  EventDispatcherInterface: Symbol.for('EventDispatcherInterface'),
  FailedEventRepositoryInterface: Symbol.for('FailedEventRepositoryInterface'),
  ApplicationVersionRepositoryInterface: Symbol.for(
    'ApplicationVersionRepositoryInterface',
  ),
  PasswordHasherInterface: Symbol.for('PasswordHasherInterface'),
  UuidRepositoryInterface: Symbol.for('UuidRepositoryInterface'),
  WebSocketServerInterface: Symbol.for('WebSocketServerInterface'),
  LoginService: Symbol.for('LoginService'),
  RefreshTokenRepositoryInterface: Symbol.for(
    'RefreshTokenRepositoryInterface',
  ),
  DocumentRepositoryInterface: Symbol.for('DocumentRepositoryInterface'),
  DocumentsRepositoryInterface: Symbol.for('DocumentsRepositoryInterface'),
  DocumentAccessRepositoryInterface: Symbol.for(
    'DocumentAccessRepositoryInterface',
  ),
  UserRepositoryInterface: Symbol.for('UserRepositoryInterface'),
  UserService: Symbol.for('UserService'),
  ErrorHandlerMiddleware: Symbol.for('ErrorHandlerMiddleware'),
  CorsMiddleware: Symbol.for('CorsMiddleware'),
  TimeoutMiddleware: Symbol.for('TimeoutMiddleware'),
  NotFoundMiddleware: Symbol.for('NotFoundMiddleware'),
  ApplicationFactoryInterface: Symbol.for('ApplicationFactoryInterface'),
  FilesystemInterface: Symbol.for('FilesystemInterface'),
  ClockInterface: Symbol.for('ClockInterface'),
}
